#include "SerpentExecutioner.h"
#include "SerpentTimeStepper.h"

#include "header.h"
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

registerMooseObject("ChrysalisApp", SerpentExecutioner);

template <>
InputParameters
validParams<SerpentExecutioner>()
{
  InputParameters params = validParams<Transient>();

  params += validParams<MutableCoefficientsInterface>();

  params.addClassDescription("Executioner for coupling to the Serpent Reactor Physics MC code "
                             "developed at VTT, Finland");

  params.addRequiredParam<std::string>("serpent_input",
                                       "Name of the main Serpent input file. The Serpent input "
                                       "must include the line(s) \"ifc 'file_name'.ifc\" for one "
                                       "or both of the density and temperature file names.");
  params.addParam<std::string>("serpent_density_file",
                               "",
                               "This file will be generated by SerpentExecutioner, and is the name "
                               "of the multiphysics file that Serpent expects to find the density "
                               "coefficients in. This corresponds to the line \"ifc "
                               "'file_name'.ifc\" in the Serpent input, with an interface type of "
                               "''" STR(IFC_TYPE_FET_DENSITY) "''.");
  params.addParam<std::string>("serpent_temperature_file",
                               "",
                               "This file will be generated by SerpentExecutioner, and is the name "
                               "of the multiphysics file that Serpent expects to find the "
                               "temperature values in. This corresponds to the line \"ifc "
                               "'file_name'.ifc\" in the Serpent input, with an interface type of "
                               "''" STR(IFC_TYPE_FET_TEMP) "''.");
  params.addParam<std::string>(
      "serpent_fission_power_file",
      "fet.pwr",
      "The name of the file to which Serpent should write the fission power FETs.");

  params.addParam<Real>(
      "integral_power_level_const",
      "Total power to which the fission power density FETs should be normalized.");
  params.addParam<FunctionName>("integral_power_level_function",
                                "A function describing the total power to which the fission power "
                                "density FETs should be normalized.");

  return params;
}

SerpentExecutioner::SerpentExecutioner(const InputParameters & parameters)
  : Transient(parameters),
    MutableCoefficientsInterface(this, parameters),
    _serpent_input_file_name(getParam<std::string>("serpent_input")),
    _serpent_interface_density_file_name(getParam<std::string>("serpent_density_file")),
    _serpent_interface_temperature_file_name(getParam<std::string>("serpent_temperature_file"))
{
  if (_serpent_interface_density_file_name.empty() &&
      _serpent_interface_temperature_file_name.empty())
    mooseError("Either \"serpent_density_file\" or \"serpent_temperature_file\" must be set!");
}

void
SerpentExecutioner::init()
{
  // Override the default time stepper behavior here, essentially copied from Transient
  if (!_time_stepper.get())
  {
    InputParameters pars = _app.getFactory().getValidParams("SerpentTimeStepper");
    pars.set<SubProblem *>("_subproblem") = &_problem;
    pars.set<FEProblemBase *>("_fe_problem_base") = &_problem;
    pars.set<Transient *>("_executioner") = this;

    if (!_pars.isParamSetByAddParam("end_time") && !_pars.isParamSetByAddParam("num_steps") &&
        _pars.isParamSetByAddParam("dt"))
      pars.set<Real>("dt") = (getParam<Real>("end_time") - getParam<Real>("start_time")) /
                             static_cast<Real>(getParam<unsigned int>("num_steps"));
    else
      pars.set<Real>("dt") = getParam<Real>("dt");

    pars.set<bool>("reset_dt") = getParam<bool>("reset_dt");
    _time_stepper =
        _app.getFactory().create<TimeStepper>("SerpentTimeStepper", "TimeStepper", pars);
  }

  // Perform the rest of the default init() actions
  Transient::init();
}

void
SerpentExecutioner::postExecute()
{
  // Perform the default postExecute() actions, which includes the TimeStepper's postExecute()
  Transient::postExecute();

  // Get the FET coefficients from Serpent here
}

void
SerpentExecutioner::preExecute()
{
  // Get the local coefficients and write them to the interface file
}
