#include "Chrysalis.GitApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<Chrysalis.GitApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

Chrysalis.GitApp::Chrysalis.GitApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  Chrysalis.GitApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  Chrysalis.GitApp::associateSyntax(_syntax, _action_factory);
}

Chrysalis.GitApp::~Chrysalis.GitApp()
{
}

// External entry point for dynamic application loading
extern "C" void Chrysalis.GitApp__registerApps() { Chrysalis.GitApp::registerApps(); }
void
Chrysalis.GitApp::registerApps()
{
  registerApp(Chrysalis.GitApp);
}

// External entry point for dynamic object registration
extern "C" void Chrysalis.GitApp__registerObjects(Factory & factory) { Chrysalis.GitApp::registerObjects(factory); }
void
Chrysalis.GitApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void Chrysalis.GitApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { Chrysalis.GitApp::associateSyntax(syntax, action_factory); }
void
Chrysalis.GitApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
